### ISSUE TITLE
Download link is empty

### ISSUE THREAD

**Issue by electricmanlpl** [uzh-rpg/rpg_svo_example#1]
Hi,
Thanks for releasing the exciting academic work, I am glad to test it, but it seems the binary link is empty.

**Comment by zhangzichao** [comment]
Hi, did you fill in the form following the link (http://rpg.ifi.uzh.ch/svo2.html)? You should receive an email containing the download links after that.

**Comment by electricmanlpl** [comment]
@zhangzichao when I click the link, it's like this
![image](https://user-images.githubusercontent.com/6188188/28347379-46d8bada-6c69-11e7-9669-9b3b888a4a7c.png)
There's no any form...

**Comment by zhangzichao** [comment]
Just click the link under the second paragraph... sorry maybe we should make it more explicit

**Comment by electricmanlpl** [comment]
I did click the link, it's straightforward... I mean after I click it and enter a new page, there's nothing except the contents:
![image](https://user-images.githubusercontent.com/6188188/28356706-968fefe4-6c9b-11e7-92db-78e775e9f971.png)

**Comment by zhangzichao** [comment]
Ah, it should be something like this
![svo_download](https://user-images.githubusercontent.com/1443111/28358751-3f2f4b30-6c70-11e7-8e9e-bdfc4ba67a36.png)
Maybe trying another browser? Or wait a bit for it to load if the internet is slow.
