### ISSUE TITLE
Installation Help

### ISSUE THREAD

**Issue by BirBikram** [uzh-rpg/rpg_svo_example#35]
Hi, 
Bit confused with your installation instruction. 
In the install.md file, it says that "Copy the svo_install_ws to where you want to install the binaries", which svo_install_ws ar eyou talking about? In the repository there are not file named that.
Is there a easy way to install this in cakin workspace?
Thanks in advance for you help.
Bikram

**Comment by BirBikram** [comment]
It was in the binaries, found it.

**Comment by sbyebss** [comment]
Hello! Could you provide me with the svo 2.0 binaries please? It seems that the robotics and perception lab doesn't provide it anymore.
