### ISSUE TITLE
fatal error: svo/common/types.h: No such file or directory

### ISSUE THREAD

**Issue by rahulsharma11** [uzh-rpg/rpg_svo_example#48]
Hi, while catkin build, i got error-

~/svo_install_overlay_ws/src/rpg_svo_example/svo_ros/include/svo_ros/svo_interface.h:11:30: fatal error: svo/common/types.h: No such file or directory
 #include <svo/common/types.h>
                              ^
compilation terminated.
CMakeFiles/svo_ros.dir/build.make:62: recipe for target 'CMakeFiles/svo_ros.dir/src/svo_interface.cpp.o' failed
make[2]: *** [CMakeFiles/svo_ros.dir/src/svo_interface.cpp.o] Error 1
CMakeFiles/Makefile2:404: recipe for target 'CMakeFiles/svo_ros.dir/all' failed
make[1]: *** [CMakeFiles/svo_ros.dir/all] Error 2
Makefile:140: recipe for target 'all' failed
make: *** [all] Error 2

Any solution?
Thanks.

**Comment by rahulsharma11** [comment]
Hi, Got that.

**Comment by ktiwari9** [comment]
Hi,
I have the same error. How did you fix it?

**Comment by rahulsharma11** [comment]
Hi,
you can locate the file and make it available in the given directory.

**Comment by Wingmore** [comment]
@rahulsharma11 how do you make it available?

**Comment by edgar-explorer** [comment]
@Wingmore @rahulsharma11  I also want to know.

**Comment by rahulsharma11** [comment]
@Wingmore , @cumtchenchang ,
You can provide the include path of given file in the CMakeList. Or you can copy the file directly to the include directory.
